todo/tarefas/urls.py
from django.urls import path
from . import views

app_name = 'tarefa'
urlpatterns = [
    path('lista-categorias/', views.lista_categorias, name='lista_categorias'),
    path('nova-categoria/', views.nova_categoria, name='nova_categoria'),
    path('editar-categoria/?<id_categoria>', views.editar_categoria, name='editar_categoria'),
    path('delete-categoria/?<id_categoria>', views.delete_categoria, name='delete_categoria'),
    path('nova-tarefa/', views.nova_tarefa, name='nova_tarefa'),
    path('editar-tarefa/?<id_tarefa>', views.editar_tarefa, name='editar_tarefa'),
    path('delete-tarefa/?<id_tarefa>', views.delete_tarefa, name='delete_tarefa'),
    path('buscar', views.search, name='search'),
    path('detalhes-tarefa/?<id_tarefa>', views.detalhes_tarefa, name='detalhes_tarefa'),
]

todo/urls.py
from django.contrib import admin
from django.urls import path, include

from todo.core.views import home
from todo.tarefas import urls as tarefas_urls
from todo.accounts import urls as accounts_urls

urlpatterns = [
    path('', home, name='core'),
    path('tarefas/', include(tarefas_urls, namespace='tarefas')),
    path('accounts/', include(accounts_urls, namespace='accounts')),
    path('admin/', admin.site.urls),
]

todo/core/models.py
from django.db import models

# Create your models here.

todo/tarefas/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class TarefaManager(models.Manager):
    def search(self, query, user):
        return self.get_queryset().filter(models.Q(nome__icontains=query) | models.Q(descricao__icontains=query) | models.Q(categoria__nome__icontains=query), user=user)

class Categoria(models.Model):
    nome = models.CharField(u'Nome', max_length=100)
    descricao = models.TextField(u'Descrição')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.nome

class Tarefa(models.Model):
    PRIORIDADE_CHOICES = (
        ('B', 'Baixa'),
        ('M', 'Média'),
        ('A', 'Alta'),
    )
    CONCLUIDA = 'C'
    CANCELADA = 'CD'
    STATUS_CHOICES = (
        (CONCLUIDA, 'Concluída'),
        (CANCELADA, 'Cancelada'),
    )
    nome = models.CharField(u'Nome', max_length=100)
    descricao = models.TextField(u'Descrição', blank=True)
    data_final = models.DateField(u'Data final')
    prioridade = models.CharField(u'Prioridade', max_length=1, choices=PRIORIDADE_CHOICES)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, verbose_name='Categoria')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(u'Status', max_length=5, choices=STATUS_CHOICES, blank=True, default='')

    objects = TarefaManager()

    def __str__(self):
        return self.nome

todo/core/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from todo.tarefas.models import Tarefa

# Create your views here.

@login_required
def home(request):
    tarefas = Tarefa.objects.filter(user=request.user, status='')
    return render(request, 'core/index.html', {'tarefas': tarefas})

todo/core/templates/core/index.html
{% extends "base.html" %}

{% block body %}
<div class="row">
    <h1>Lista de Tarefas</h1>
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-danger">
            {{ message }}
        </div>
        {% endfor %}
    {% endif %}
    {% if tarefas %}
    <table class="table">
        <thead>
            <tr>
                <th>Tarefa</th>
                <th>Descrição</th>
                <th>Data final</th>
                <th>Prioridade</th>
                <th>Categoria</th>
                <th colspan="2" style="textalign:center">Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for t in tarefas %}
            <tr>
                <td>{{ t.nome }}</td>
                <td>{{ t.descricao }}</td>
                <td>{{ t.data_final }}</td>
                <td>{{ t.get_prioridade_display }}</td>
                <td>{{ t.categoria }}</td>
                <td><a href="{% url 'tarefas:editar_tarefa' t.id %}" class="btn btn-info btn-sm">Editar</a></td>
                <td><a href="{% url 'tarefas:delete_tarefa' t.id %}" class="btn btn-danger btn-sm">Excluir</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p> </p>
    <div class="alert alert-info" role="alert">
        <p>Não há nenhuma tarefa cadastrada!</p>
    </div>
    {% endif %}
    <a href="{% url 'tarefas:nova_tarefa' %}" class="btn btn-primary" role="button">Adicionar tarefa</a>
</div>
{% endblock body %}