todo/tarefas/urls.py
from django.urls import path
from . import views

app_name = 'tarefa'
urlpatterns = [
    path('lista-categorias/', views.lista_categorias, name='lista_categorias'),
    path('nova-categoria/', views.nova_categoria, name='nova_categoria'),
    path('editar-categoria/?<id_categoria>', views.editar_categoria, name='editar_categoria'),
    path('delete-categoria/?<id_categoria>', views.delete_categoria, name='delete_categoria'),
    path('nova-tarefa/', views.nova_tarefa, name='nova_tarefa'),
    path('editar-tarefa/?<id_tarefa>', views.editar_tarefa, name='editar_tarefa'),
    path('delete-tarefa/?<id_tarefa>', views.delete_tarefa, name='delete_tarefa'),
    path('buscar', views.search, name='search'),
    path('detalhes-tarefa/?<id_tarefa>', views.detalhes_tarefa, name='detalhes_tarefa'),
]

todo/urls.py
from django.contrib import admin
from django.urls import path, include

from todo.core.views import home
from todo.tarefas import urls as tarefas_urls
from todo.accounts import urls as accounts_urls

urlpatterns = [
    path('', home, name='core'),
    path('tarefas/', include(tarefas_urls, namespace='tarefas')),
    path('accounts/', include(accounts_urls, namespace='accounts')),
    path('admin/', admin.site.urls),
]

todo/tarefas/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class TarefaManager(models.Manager):
    def search(self, query, user):
        return self.get_queryset().filter(models.Q(nome__icontains=query) | models.Q(descricao__icontains=query) | models.Q(categoria__nome__icontains=query), user=user)

class Categoria(models.Model):
    nome = models.CharField(u'Nome', max_length=100)
    descricao = models.TextField(u'Descrição')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.nome

class Tarefa(models.Model):
    PRIORIDADE_CHOICES = (
        ('B', 'Baixa'),
        ('M', 'Média'),
        ('A', 'Alta'),
    )
    CONCLUIDA = 'C'
    CANCELADA = 'CD'
    STATUS_CHOICES = (
        (CONCLUIDA, 'Concluída'),
        (CANCELADA, 'Cancelada'),
    )
    nome = models.CharField(u'Nome', max_length=100)
    descricao = models.TextField(u'Descrição', blank=True)
    data_final = models.DateField(u'Data final')
    prioridade = models.CharField(u'Prioridade', max_length=1, choices=PRIORIDADE_CHOICES)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, verbose_name='Categoria')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(u'Status', max_length=5, choices=STATUS_CHOICES, blank=True, default='')

    objects = TarefaManager()

    def __str__(self):
        return self.nome

todo/tarefas/forms.py
from django import forms
from .models import Categoria, Tarefa

class CategoriaForm(forms.ModelForm):
    nome = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    descricao = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))
    class Meta:
        model = Categoria
        exclude = (id, 'user',)

class TarefaForm(forms.ModelForm):
    class Meta:
        model = Tarefa
#        fields = '__all__'
        exclude = (id, 'user',)

    def __init__(self, user=None, *args, **kwargs):
        super(TarefaForm, self).__init__(*args, **kwargs)
        if user is not None:
            self.fields['categoria'].queryset = Categoria.objects.filter(user=user)

todo/tarefas/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .forms import CategoriaForm, TarefaForm
from .models import Categoria, Tarefa

# Create your views here.

# Categoria
@login_required
def nova_categoria(request):
    if request.method == 'POST':
        form = CategoriaForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.user = request.user
            f.save()
            return redirect('tarefas:lista_categorias')
        else:
            print(form.errors)
    else:
        form = CategoriaForm()
    return render(request, 'tarefas/nova_categoria.html', {'form': form})

@login_required
def lista_categorias(request):
    categorias = Categoria.objects.filter(user=request.user)
    return render(request, 'tarefas/lista_categorias.html', {'categorias': categorias})

@login_required
def delete_categoria(request, id_categoria):
    categoria = Categoria.objects.get(id=id_categoria)
    if categoria.user == request.user:
        categoria.delete()
    else:
        messages.error(request, 'Você não tem permissão para excluir essa categoria!')
        return render(request, 'tarefas/lista_categorias.html')
    return redirect('tarefas:lista_categorias')

@login_required
def editar_categoria(request, id_categoria):
    categoria = get_object_or_404(Categoria, id=id_categoria, user=request.user)
    if request.method == 'POST':
        form = TarefaForm(request.POST, instance=categoria)
        if form.is_valid():
            form.save()
            return redirect('core')
    else:
        form = TarefaForm(instance=categoria)
    return render(request, 'tarefas/nova_categoria.html', {'form': form})


# Tarefa
@login_required
def nova_tarefa(request):
    if request.method == 'POST':
        form = TarefaForm(user=request.user, data=request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.user = request.user
            f.save()
            return redirect('core')
        else:
            print(form.errors)
    else:
        form = TarefaForm(user=request.user)
    return render(request, 'tarefas/nova_tarefa.html', {'form': form})

@login_required
def delete_tarefa(request, id_tarefa):
    tarefa = Tarefa.objects.get(id=id_tarefa)
    if tarefa.user == request.user:
        tarefa.delete()
    else:
        messages.error(request, 'Você não tem permissão para excluir essa tarefa!')
        return render(request, 'core/index.html')
    return redirect('core')

@login_required
def editar_tarefa(request, id_tarefa):
    tarefa = get_object_or_404(Tarefa, id=id_tarefa, user=request.user)
    if request.method == 'POST':
        form = TarefaForm(user=request.user, data=request.POST, instance=tarefa)
        if form.is_valid():
            form.save()
            return redirect('core')
    else:
        form = TarefaForm(user=request.user, instance=tarefa)
    return render(request, 'tarefas/nova_tarefa.html', {'form': form})

@login_required
def search(request):
    q = request.GET.get('search')
    if q is not None:
        result = Tarefa.objects.search(q, request.user)
    return render(request, 'tarefas/pagina_resultado.html', {'result': result})

@login_required
def detalhes_tarefa(request, id_tarefa):
    tarefa = get_object_or_404(Tarefa, id=id_tarefa, user=request.user)
    return render(request, 'tarefas/detalhes_tarefa.html', {'tarefa': tarefa})

todo/tarefas/templates/tarefas/detalhes_tarefa.html
{% extends "base.html" %}

{% block body %}
<h1>Detalhes da Tarefa</h1>
<div class="row">
    <form class="" action="" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="">Nome</label>
            {{ tarefa.nome }}
        </div>
        <div class="form-group">
            <label for="">Descrição</label>
            {{ tarefa.descricao }}
        </div>
        <div class="form-group">
            <label for="">Data final</label>
            {{ tarefa.data_final }}
        </div>
        <div class="form-group">
            <label for="">Prioridade</label>
            {{ tarefa.get_prioridade_display }}
        </div>
        <div class="form-group">
            <label for="">Categoria</label>
            {{ tarefa.categoria }}
        </div>
    </form>
</div>
{% endblock body %}

todo/tarefas/templates/tarefas/lista_categorias.html
{% extends "base.html" %}

{% block body %}
<div class="row">
    <h1>Lista de Categorias</h1>
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-danger">
            {{ message }}
        </div>
        {% endfor %}
    {% endif %}
    {% if categorias %}
    <table class="table">
        <thead>
            <tr>
                <th>Categoria</th>
                <th>Descrição</th>
                <th colspan="2" style="textalign:center">Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for c in categorias %}
            <tr>
                <td>{{ c.nome }}</td>
                <td>{{ c.descricao }}</td>
                <td><a href="{% url 'tarefas:editar_categoria' c.id %}" class="btn btn-info btn-sm">Editar</a></td>
                <td><a href="{% url 'tarefas:delete_categoria' c.id %}" class="btn btn-danger btn-sm">Excluir</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p>&nbsp;</p>
    <div class="alert alert-info" role="alert">
        <p>Não há nenhuma categoria cadastrada!</p>
    </div>
    {% endif %}
    <a href="{% url 'tarefas:nova_categoria' %}" class="btn btn-primary" role="button">Adicionar categoria</a>
</div>
{% endblock body %}

todo/tarefas/templates/tarefas/nova_categoria.html
{% extends "base.html" %}

{% block body %}
<h1>Nova Categoria</h1>
<div class="row">
    <form class="" action="" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.nome.id_for_label }}">Nome</label>
            {{ form.nome }}
        </div>
        <div class="form-group">
            <label for="{{ form.descricao.id_for_label }}">Descrição</label>
            {{ form.descricao }}
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Salvar</button>
        </div>
    </form>
</div>
{% endblock body %}

todo/tarefas/templates/tarefas/nova_tarefa.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block body %}
<h1>Tarefa</h1>
<div class="row">
    <form class="" action="" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.nome.id_for_label }}">Nome</label>
            {{ form.nome|add_class:"form-control"}}
        </div>
        <div class="form-group">
            <label for="{{ form.descricao.id_for_label }}">Descrição</label>
            {{ form.descricao|add_class:"form-control" }}
        </div>
        <div class="form-group">
            <label for="{{ form.data_final.id_for_label }}">Data final</label>
            {{ form.data_final|add_class:"form-control"|attr:'type:date' }}
        </div>
        <div class="form-group">
            <label for="{{ form.prioridade.id_for_label }}">Prioridade</label>
            {{ form.prioridade|add_class:"form-control" }}
        </div>
        <div class="form-group">
            <label for="{{ form.categoria.id_for_label }}">Categoria</label>
            {{ form.categoria|add_class:"form-control" }}
        </div>
        {% if form.instance.id %}
        <div class="form-group">
            <label for="{{ form.status.id_for_label }}">Status</label>
            {{ form.status|add_class:"form-control" }}
        </div>
        {% endif %}
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Salvar</button>
        </div>
    </form>
</div>
{% endblock body %}

todo/tarefas/templates/tarefas/pagina_resultado.html
{% extends "base.html" %}

{% block body %}
    <div class="row">
        <h1>Resultado da busca</h1><br>
        {% if result %}
        {% for r in result %}
            <a href="{% url 'tarefas:detalhes_tarefa' r.id %}"><h3>{{ r.nome }}</h3></a>
        {% endfor %}
        {% else %}
            <div class="alert alert-info">
                <p>Nenhuma tarefa encontrada!</p>
            </div>
        {% endif %}
    </div>
{% endblock %}