todo/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('novo-usuario/', views.add_user, name='add_user'),
    path('login-usuario/', views.user_login, name='user_login'),
    path('logout-usuario/', views.user_logout, name='user_logout'),
    path('alterar-senha/', views.change_password, name='change_password'),
]

todo/urls.py
from django.contrib import admin
from django.urls import path, include

from todo.core.views import home
from todo.tarefas import urls as tarefas_urls
from todo.accounts import urls as accounts_urls

urlpatterns = [
    path('', home, name='core'),
    path('tarefas/', include(tarefas_urls, namespace='tarefas')),
    path('accounts/', include(accounts_urls, namespace='accounts')),
    path('admin/', admin.site.urls),
]

todo/accounts/models.py
from django.db import models

# Create your models here.

todo/accounts/forms.py
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'password')

todo/accounts/views.py
from django.shortcuts import render, redirect
#from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages

from .forms import UserForm

# Create your views here.

def add_user(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            u = form.save()
            u.set_password(u.password)
            u.save()
            messages.sucess(request, 'Usuário criado com sucesso! Utilize o formulário abaixo para fazer login.')
            return redirect('accounts:user_login')
    else:
        form = UserForm()
    return render(request, 'accounts/add_user.html', {'form': form})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
            return redirect(request.GET.get('next', '/'))
        else:
            messages.error(request, 'Usuário ou senha inválidos!')
    return render(request, 'accounts/user_login.html')

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Senha alterada com sucesso!')
            return redirect('accounts:change_password')
        else:
            messages.error(request, 'Não foi possível alterar a sua senha!')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'accounts/change_password.html', {'form': form})

def user_logout(request):
    logout(request)
    return redirect('accounts:user_login')

todo/accounts/templates/accounts/add_user.html
{% load staticfiles %}
{% load widget_tweaks %}
<!doctype html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Cadastro de novo usuário</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  </head>

  <body>
    <div class="container">
        <h1>Informe os dados</h1>
        <div class="row">
            <form class="" action="" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="{{ form.first_name.id_for_label }}">Nome</label>
                    {{ form.first_name|add_class:'form-control'|attr:'autofocus' }}
                </div>
                <div class="form-group">
                    <label for="{{ form.last_name.id_for_label }}">Sobrenome</label>
                    {{ form.last_name|add_class:'form-control' }}
                </div>
                <div class="form-group">
                    <label for="{{ form.last_name.id_for_label }}">Usuário</label>
                    {{ form.username|add_class:'form-control' }}
                </div>
                <div class="form-group">
                    <label for="{{ form.password.id_for_label }}">Senha</label>
                    {{ form.password|add_class:'form-control'|attr:'type:search' }}
                </div>
                <button class="btn btn-primary" type="submit">Cadastrar</button>
                <a href="{% url 'accounts:user_login' %}">Fazer login</a>
            </form>
        </div>
    </div>
  </body>
</html>
</html>

todo/accounts/templates/accounts/change_password.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block body %}
    <h1>Trocar a senha</h1>
    {% if messages %}
        <div class="alert alert-warning">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </div>
    {% endif %}
    <form class="" action="" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.old_password.id_for_label }}">Senha antiga</label>
            {{ form.old_password|add_class:"form-control"|attr:"autofocus" }}
        </div>
        <div class="form-group">
            <label for="{{ form.new_password1.id_for_label }}">Nova senha</label>
            {{ form.new_password1|add_class:"form-control" }}
        </div>
        <div class="form-group">
            <label for="{{ form.new_password2.id_for_label }}">Confirmar nova senha</label>
            {{ form.new_password2|add_class:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Alterar</button>
    </form>

{% endblock %}

todo/accounts/templates/accounts/user_login.html
{% load staticfiles %}
{% load widget_tweaks %}
<!doctype html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Login</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/signin.css' %}" rel="stylesheet">
  </head>

  <body class="text-center">
    <form class="form-signin" method="post">
      {% csrf_token %}
      <img class="mb-4" src="https://getbootstrap.com/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
      <h1 class="h3 mb-3 font-weight-normal">Por favor faça o login</h1>
      {% if messages %}
        <div class="alert alert-danger" role="alert">
          {% for message in messages %}
             {{ message }}
          {% endfor %}
        </div>
      {% endif %}
      <label for="username" class="sr-only">Usuário</label>
      <input type="text" id="username" name="username" class="form-control" placeholder="Informe o usuário" required autofocus>
      <label for="password" class="sr-only">Senha</label>
      <input type="password" id="password" name="password" class="form-control" placeholder="Informe a senha" required>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Entrar</button>
      <a href="{% url 'accounts:add_user' %}" class="btn btn-lg btn-primary btn-info">Não tem cadastro?</a>
    </form>
  </body>
</html>