todo/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('novo-usuario/', views.add_user, name='add_user'),
    path('login-usuario/', views.user_login, name='user_login'),
    path('logout-usuario/', views.user_logout, name='user_logout'),
    path('alterar-senha/', views.change_password, name='change_password'),
]

todo/tarefas/urls.py
from django.urls import path
from . import views

app_name = 'tarefa'
urlpatterns = [
    path('lista-categorias/', views.lista_categorias, name='lista_categorias'),
    path('nova-categoria/', views.nova_categoria, name='nova_categoria'),
    path('editar-categoria/?<id_categoria>', views.editar_categoria, name='editar_categoria'),
    path('delete-categoria/?<id_categoria>', views.delete_categoria, name='delete_categoria'),
    path('nova-tarefa/', views.nova_tarefa, name='nova_tarefa'),
    path('editar-tarefa/?<id_tarefa>', views.editar_tarefa, name='editar_tarefa'),
    path('delete-tarefa/?<id_tarefa>', views.delete_tarefa, name='delete_tarefa'),
    path('buscar', views.search, name='search'),
    path('detalhes-tarefa/?<id_tarefa>', views.detalhes_tarefa, name='detalhes_tarefa'),
]

todo/urls.py
from django.contrib import admin
from django.urls import path, include

from todo.core.views import home
from todo.tarefas import urls as tarefas_urls
from todo.accounts import urls as accounts_urls

urlpatterns = [
    path('', home, name='core'),
    path('tarefas/', include(tarefas_urls, namespace='tarefas')),
    path('accounts/', include(accounts_urls, namespace='accounts')),
    path('admin/', admin.site.urls),
]

todo/core/models.py
from django.db import models

# Create your models here.

todo/core/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from todo.tarefas.models import Tarefa

# Create your views here.

@login_required
def home(request):
    tarefas = Tarefa.objects.filter(user=request.user, status='')
    return render(request, 'core/index.html', {'tarefas': tarefas})

todo/core/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>ToDo</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/signin.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/starter-template.css' %}" rel="stylesheet">
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="#">ToDo</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'tarefas:lista_categorias' %}">Categorias</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'tarefas:nova_tarefa' %}">Tarefas</a>
          </li>
          <li></li>
          <li>
            <form class="form-inline my-2 my-sm-0" action="{% url 'tarefas:search' %}">
              <input class="form-control mr-sm-2" type="text" placeholder="Busca" aria-label="Search" name="search">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
            </form>
          </li>
        </ul>
        <ul class="navbar-nav navbar-right">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% if user.is_authenticated %}{{ user.get_full_name|default:user.username}}{% endif %}</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="{% url 'accounts:change_password' %}">Alterar a senha</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'accounts:user_logout' %}">Sair</a>
            </div>
          </li>
        </ul>
      </div>
    </nav>

    <div class="container">
    {% block body %}

    {% endblock body %}
    </div><!-- /.container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="{% static 'js/jquery-slim.min.js' %}"><\/script>')</script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>